[project]
name = "Scalib"
version = "0.1.0"
description = "A musical scale generation and manipulation library"

[build.system]
requires = ["setuptools>=65.5"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
